favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

avatar:
  author_photo: /images/avatar.png
  author_nickname: Gabe Coates
  path: /

gtag:
  enable: true
  gtagkey: G-N5BY7X2TGE

comments:
  enable: true

  gitalk:
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.pathname
    distractionFreeMode: false

  valine:
    enable: false
    appId:
    appKey:
    placeholder: Welcome!
    avatar: retro
    vempty_display: false

  disqus:
    enable: false
    shortname: https-zxcxxxx-github-io
  
  waline:
    enable: false
    serverURL:

navbar:
  -
    name: Home
    enable: true
    path: /
    key: home
  -
    name: Archives
    enable: true
    path: /archives/
    key: archives
  -
    name: Categories
    enable: false
    path: /categories/
    key: categories
  -
    name: Tags
    enable: true
    path: /tags/
    key: tags
  -
    name: Friends
    enable: false
    path: /friends/
    key: friends
  -
    name: About
    enable: true
    path: /about/
    key: about

catalog:
  enable: true

prevnext:
  enable: true

friends:
  -
    nickname: Hexo
    site: https://hexo.io/
    meta:

footer:
  social:
    -
      name: linkedin
      icon: linkedin
      path: https://linkedin.com/in/gabecoates
    -
      name: github
      icon: github
      path: https://github.com/gabecoatess/
    -
      name: email
      icon: envelope
      path: mailto:gabrielrcoates@outlook.com

  more:
    -
      name: Copyright © {thisYear} Gabriel Coates
      path: https://gabecoatess.com/

search:
  enable: true
  placeholder: 

colorSwitch:
  enable: true

postShare:
  enable: true

  twitter:
    enable: true

  facebook:
    enable: true

codeBlock:
  style: 'normal'
  copy:
    enable: true

mathjax:
  enable: true

cdns:
  jquery:
    enable: false
    url: https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js

  fancybox:
    enable: false
    url:
      css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
      js: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

  mathjax:
    enable: false
    url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

  clipboard:
    enable: false
    url: https://cdn.jsdelivr.net/npm/clipboard@2.0.10/dist/clipboard.min.js

  comments:
    gitalk:
      enable: false
      url:
        css: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
        js: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js

    valine:
      enable: false
      url: https://cdn.jsdelivr.net/npm/valine@1.4.18/dist/Valine.min.js

    waline:
      enable: false
      url: https://cdn.jsdelivr.net/npm/@waline/client@2.5.1/dist/legacy.min.js

themeColor: '#808080'
